# regions.py

REGIONS = [
    # България — области
    {"region": "Благоевград",    "slug": "oblast-blagoevgrad"},
    {"region": "Бургас",         "slug": "oblast-burgas"},
    {"region": "Варна",           "slug": "oblast-varna"},
    {"region": "Велико Търново",  "slug": "oblast-veliko-tarnovo"},
    {"region": "Видин",           "slug": "oblast-vidin"},
    {"region": "Враца",           "slug": "oblast-vratsa"},
    {"region": "Габрово",         "slug": "oblast-gabrovo"},
    {"region": "Добрич",          "slug": "oblast-dobrich"},
    {"region": "Кърджали",        "slug": "oblast-kardzhali"},
    {"region": "Кюстендил",       "slug": "oblast-kyustendil"},
    {"region": "Ловеч",           "slug": "oblast-lovech"},
    {"region": "Монтана",         "slug": "oblast-montana"},
    {"region": "Пазарджик",       "slug": "oblast-pazardzhik"},
    {"region": "Перник",          "slug": "oblast-pernik"},
    {"region": "Плевен",          "slug": "oblast-pleven"},
    {"region": "Пловдив",         "slug": "oblast-plovdiv"},
    {"region": "Разград",         "slug": "oblast-razgrad"},
    {"region": "Русе",            "slug": "oblast-ruse"},
    {"region": "Силистра",        "slug": "oblast-silistra"},
    {"region": "Сливен",          "slug": "oblast-sliven"},
    {"region": "Смолян",          "slug": "oblast-smolyan"},
    {"region": "София",           "slug": "oblast-sofiya"},
    {"region": "Стара Загора",    "slug": "oblast-stara-zagora"},
    {"region": "Търговище",       "slug": "oblast-targovishte"},
    {"region": "Хасково",         "slug": "oblast-haskovo"},
    {"region": "Шумен",           "slug": "oblast-shumen"},
    {"region": "Ямбол",           "slug": "oblast-yambol"},

    # България — градове
    {"region": "Благоевград",    "slug": "grad-blagoevgrad"},
    {"region": "Бургас",         "slug": "grad-burgas"},
    {"region": "Варна",           "slug": "grad-varna"},
    {"region": "Велико Търново",  "slug": "grad-veliko-tarnovo"},
    {"region": "Видин",           "slug": "grad-vidin"},
    {"region": "Враца",           "slug": "grad-vratsa"},
    {"region": "Габрово",         "slug": "grad-gabrovo"},
    {"region": "Добрич",          "slug": "grad-dobrich"},
    {"region": "Кърджали",        "slug": "grad-kardzhali"},
    {"region": "Кюстендил",       "slug": "grad-kyustendil"},
    {"region": "Ловеч",           "slug": "grad-lovech"},
    {"region": "Монтана",         "slug": "grad-montana"},
    {"region": "Пазарджик",       "slug": "grad-pazardzhik"},
    {"region": "Перник",          "slug": "grad-pernik"},
    {"region": "Плевен",          "slug": "grad-pleven"},
    {"region": "Пловдив",         "slug": "grad-plovdiv"},
    {"region": "Разград",         "slug": "grad-razgrad"},
    {"region": "Русе",            "slug": "grad-ruse"},
    {"region": "Силистра",        "slug": "grad-silistra"},
    {"region": "Сливен",          "slug": "grad-sliven"},
    {"region": "Смолян",          "slug": "grad-smolyan"},
    {"region": "София",           "slug": "grad-sofiya"},
    {"region": "Стара Загора",    "slug": "grad-stara-zagora"},
    {"region": "Търговище",       "slug": "grad-targovishte"},
    {"region": "Хасково",         "slug": "grad-haskovo"},
    {"region": "Шумен",           "slug": "grad-shumen"},
    {"region": "Ямбол",           "slug": "grad-yambol"},
]
